[phases.setup]
nixPkgs = ["python312", "pipenv"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmds = ["uvicorn backend.app.main:app --host=0.0.0.0 --port=8000"]
